# Generated by Django 4.1.7 on 2023-03-10 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='https?://(www\\.)?facebook\\.com/[A-Za-z0-9_.-]+/?$')], verbose_name='Facebook profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imkon_profile',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='https?://(?:www\\.)?imkon\\.uz/(?P<path>[a-zA-Z0-9/_.-]+)/?$')], verbose_name='Imkon profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkden_profile',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='https:\\/\\/www\\.linkedin\\.com\\/in\\/[a-zA-Z0-9-]+\\/?$')], verbose_name='Linkden profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_profile',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='https:\\/\\/t\\.me\\/[a-zA-Z0-9_]+')], verbose_name='Telegram profile'),
        ),
    ]
