# Generated by Django 4.1.7 on 2023-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.CharField(max_length=150, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti'),
        ),
    ]
